name: Generate Snake

on:
  schedule: # Ejecutar automáticamente todos los días a medianoche (hora UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña "Actions"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: JernelOlart
          outputs: dist/snake-github-dark.svg?palette=github-dark

      - name: Subir archivo generado al repositorio
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
